version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: phonxis/beans_shop_production_django:latest
    depends_on:
      - postgres
      - redis
    #env_file:
    #  - ./.envs/.production/.django
    #  - ./.envs/.production/.postgres
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=QcaR2ZWqaorkN52ueIRkM3bfCK8aotgud9ABkeqbInhG3Li23hJsNs2JpQM0X4ac
      - DJANGO_ADMIN_URL=gG1lPTPACQQu6hYm0faZXr49IuI6YwfZ/
      - DJANGO_ALLOWED_HOSTS=.example.com
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_SERVER_EMAIL=""
      - SENDINBLUE_API_KEY=""
      - GOOGLE_APPLICATION_CREDENTIALS=""
      - DJANGO_GCP_STORAGE_BUCKET_NAME=""
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=True
      - WEB_CONCURRENCY=4
      - REDIS_URL=redis://redis:6379/0
      - CELERY_FLOWER_USER=debug
      - CELERY_FLOWER_PASSWORD=debug
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=beans_shop
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: phonxis/beans_shop_production_postgres:latest
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    #env_file:
    #  - ./.envs/.production/.postgres
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=QcaR2ZWqaorkN52ueIRkM3bfCK8aotgud9ABkeqbInhG3Li23hJsNs2JpQM0X4ac
      - DJANGO_ADMIN_URL=gG1lPTPACQQu6hYm0faZXr49IuI6YwfZ/
      - DJANGO_ALLOWED_HOSTS=.example.com
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_SERVER_EMAIL=""
      - SENDINBLUE_API_KEY=""
      - GOOGLE_APPLICATION_CREDENTIALS=""
      - DJANGO_GCP_STORAGE_BUCKET_NAME=""
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=True
      - WEB_CONCURRENCY=4
      - REDIS_URL=redis://redis:6379/0
      - CELERY_FLOWER_USER=debug
      - CELERY_FLOWER_PASSWORD=debug
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=beans_shop
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug

  #traefik:
  #  build:
  #    context: .
  #    dockerfile: ./compose/production/traefik/Dockerfile
  #  image: beans_shop_production_traefik
  #  depends_on:
  #    - django
  #  volumes:
  #    - production_traefik:/etc/traefik/acme
  #  ports:
  #    - "0.0.0.0:80:80"
  #    - "0.0.0.0:443:443"
  #    - "0.0.0.0:5555:5555"

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: phonxis/beans_shop_production_nginx:latest
    volumes:
      - /var/www/django-static:/static
      - /var/www/django-media:/media
    expose:
      - 1337
    ports:
      - 127.0.0.1:1337:80
    depends_on:
      - django

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: phonxis/beans_shop_production_celeryworker:latest
    command: /start-celeryworker

  #celerybeat:
  #  <<: *django
  #  image: beans_shop_production_celerybeat
  #  command: /start-celerybeat

  #flower:
  #  <<: *django
  #  image: beans_shop_production_flower
  #  command: /start-flower
